import test from "node:test";
import assert from "node:assert/strict";
import { validateBriefing, normaliseBriefing } from "../src/briefing.js";
import { validateHandoff } from "../src/contracts.js";
import { sanitiseMakerFiles, validateMakerFiles, makeSrcdoc } from "../src/code-validator.js";
import { consumeRateLimit } from "../api/lib/storage.js";

const briefing={organisation_name:"Harbour Museum",organisation_type:"museum",destination:"Dublin, Ireland",engagement_problem:"Visitors miss local stories and leave quickly.",target_audience:"International adults and families",visitor_outcome:"Discover and understand lesser-known stories",resources_and_constraints:"QR codes and staff; free and mobile-first",desired_duration_minutes:45,desired_tone:"Curious and welcoming"};

test("simple brief is accepted and missing strategy is explicitly inferred",()=>{assert.equal(validateBriefing(briefing).valid,true);const normal=normaliseBriefing({...briefing,organisation_name:"  Harbour Museum  "});assert.equal(normal.organisation_name,"Harbour Museum");assert.match(normal.business_objective,/Not supplied/);assert.match(normal.inference_note,/agent inferences/)});
test("missing and invalid brief fields fail",()=>{const errors=validateBriefing({...briefing,destination:"",desired_duration_minutes:5}).errors;assert.ok(errors.some(x=>x.includes("destination")));assert.ok(errors.some(x=>x.includes("desired_duration_minutes")))});
test("Researcher must record live sourced evidence",()=>{const base={research_question:"How can the venue deepen discovery?",opportunity_diagnosis:"Visitors miss stories.",audience_needs:["Clear orientation"],business_needs:["Deeper engagement"],source_queries:[],evidence_items:[],experience_opportunities:["Connect exhibits"],constraints:["Mobile first"],unknowns:["Visitor preferences"],research_brief:"Use sourced places."};assert.equal(validateHandoff("researcher",base).valid,false);const good={...base,source_queries:[{queried_at:new Date().toISOString(),result_count:3}],evidence_items:[1,2,3].map(n=>({entity_id:`Q${n}`,source_url:`https://www.wikidata.org/wiki/Q${n}`}))};assert.equal(validateHandoff("researcher",good).valid,true)});
test("Designer is limited to authorised products and supplied evidence",()=>{const base={selected_product:"treasure_hunt",selection_rationale:"Best fit",design_goal:"Deepen discovery",experience_concept:"A clue journey",visitor_journey:["Open"],information_architecture:["Start"],interaction_specification:["Choose"],required_evidence_ids:["Q1"],content_requirements:["Welcome"],visual_direction:"Warm",accessibility_requirements:["Keyboard"],functional_requirements:["Progress"],acceptance_criteria:["Works"],known_tradeoffs:["Short"]},context={researcher:{evidence_items:[{entity_id:"Q1"}]}};assert.equal(validateHandoff("designer",base,context).valid,true);assert.equal(validateHandoff("designer",{...base,selected_product:"generic_page"},context).valid,false);assert.equal(validateHandoff("designer",{...base,required_evidence_ids:["Q999"]},context).valid,false)});
test("safe generated experience passes and dangerous code fails",()=>{const files={html:"<main><h1>Dublin Quest</h1><button id='go'>Start</button></main>",css:"body{font-family:sans-serif}",javascript:"document.querySelector('#go').addEventListener('click',()=>document.body.dataset.started='true')"};assert.equal(validateMakerFiles(files).valid,true);assert.match(makeSrcdoc(files),/Content-Security-Policy/);assert.equal(validateMakerFiles({...files,javascript:"fetch('https://example.com')"}).valid,false);assert.equal(validateMakerFiles({...files,html:'<script src="https://evil.example/x.js"></script><main><h1>X</h1></main>'}).valid,false)});
test("rate limiter allows five starts and blocks the sixth",async()=>{const id=`test-${Date.now()}`;for(let i=0;i<5;i++)assert.equal(await consumeRateLimit(id),true);assert.equal(await consumeRateLimit(id),false)});
test("sanitiser removes external and inline executable content",()=>{const clean=sanitiseMakerFiles({html:'<link href="https://x"><main><h1>X</h1><button onclick="bad()">Go</button><iframe src="https://x"></iframe></main>',css:'@import "https://x";',javascript:""});assert.equal(validateMakerFiles(clean).valid,true);assert.doesNotMatch(clean.html,/onclick|iframe|link/i)});
