import test from "node:test";
import assert from "node:assert/strict";
import { validateBriefing, normaliseBriefing } from "../src/briefing.js";
import { validateHandoff } from "../src/contracts.js";
import { sanitiseMakerFiles, validateMakerFiles, makeSrcdoc } from "../src/code-validator.js";
import { consumeRateLimit } from "../api/lib/storage.js";
import { createUsageTracker, estimateHaikuCost, reconcileToolQueries } from "../api/lib/anthropic.js";

const briefing={organisation_name:"Harbour Museum",organisation_type:"attraction",attraction_type:"museum",destination:"Dublin, Ireland",engagement_problem:"Visitors miss local stories and leave quickly.",target_audience:"International adults and families",visitor_outcome:"Discover and understand lesser-known stories",resources_and_constraints:"QR codes and staff; free and mobile-first",desired_duration_minutes:45,desired_tone:"Curious and welcoming",movement_allowed:"no",transport_modes:[]};

test("simple brief is accepted and missing strategy is explicitly inferred",()=>{assert.equal(validateBriefing(briefing).valid,true);const normal=normaliseBriefing({...briefing,organisation_name:"  Harbour Museum  "});assert.equal(normal.organisation_name,"Harbour Museum");assert.match(normal.business_objective,/Not supplied/);assert.match(normal.inference_note,/agent inference/)});
test("missing and invalid brief fields fail",()=>{const errors=validateBriefing({...briefing,destination:"",desired_duration_minutes:5}).errors;assert.ok(errors.some(x=>x.includes("destination")));assert.ok(errors.some(x=>x.includes("desired_duration_minutes")))});
test("movement and organisation scope are enforced",()=>{assert.equal(validateBriefing({...briefing,organisation_type:"museum"}).valid,false);assert.equal(validateBriefing({...briefing,movement_allowed:"yes",transport_modes:[],starting_point:""}).valid,false);const moving={...briefing,movement_allowed:"yes",starting_point:"Eyre Square, Galway",transport_modes:["walking","public_transport"]},normal=normaliseBriefing(moving);assert.equal(validateBriefing(moving).valid,true);assert.equal(normal.starting_point,"Eyre Square, Galway");assert.deepEqual(normal.transport_modes,["walking","public_transport"])});
test("Researcher evidence must trace to a live external query",()=>{const base={research_question:"How can the venue deepen discovery?",opportunity_diagnosis:"Visitors miss stories.",audience_needs:["Clear orientation"],business_needs:["Deeper engagement"],tool_decisions:[],source_queries:[],evidence_items:[],experience_opportunities:["Connect exhibits"],constraints:["Mobile first"],unknowns:["Visitor preferences"],research_brief:"Use sourced places."};assert.equal(validateHandoff("researcher",base).valid,false);const queries=[{source_query_id:"web-1",tool:"web_search",query:"museum history",queried_at:new Date().toISOString(),result_count:3}],good={...base,source_queries:queries,evidence_items:[1,2].map(n=>({entity_id:`web-${n}`,source_query_id:"web-1",source_url:`https://example.com/${n}`}))};assert.equal(validateHandoff("researcher",good).valid,true);assert.equal(validateHandoff("researcher",{...good,evidence_items:[{entity_id:"x",source_query_id:"missing",source_url:"https://example.com"}]}).valid,false)});
test("executed external tools are always present in the auditable query record",()=>{const output={source_queries:[{source_query_id:"web-1",tool:"web_search",query:"history",queried_at:"2026-01-01T00:00:00Z",result_count:2}]},calls=[{id:"tool-1",name:"compute_route",input:{travel_mode:"WALK"},result:{queried_at:"2026-01-01T00:01:00Z",result_count:1}}];reconcileToolQueries(output,calls);assert.equal(output.source_queries.length,2);assert.equal(output.source_queries[1].tool,"compute_route");reconcileToolQueries(output,calls);assert.equal(output.source_queries.length,2)});
test("Designer is limited to authorised products and supplied evidence",()=>{const base={selected_product:"treasure_hunt",selection_rationale:"Best fit",design_goal:"Deepen discovery",experience_concept:"A clue journey",visitor_journey:["Open"],information_architecture:["Start"],interaction_specification:["Choose"],required_evidence_ids:["Q1"],content_requirements:["Welcome"],visual_direction:"Warm",accessibility_requirements:["Keyboard"],functional_requirements:["Progress"],acceptance_criteria:["Works"],known_tradeoffs:["Short"]},context={researcher:{evidence_items:[{entity_id:"Q1"}]}};assert.equal(validateHandoff("designer",base,context).valid,true);assert.equal(validateHandoff("designer",{...base,selected_product:"generic_page"},context).valid,false);assert.equal(validateHandoff("designer",{...base,required_evidence_ids:["Q999"]},context).valid,false)});
test("safe generated experience passes and dangerous code fails",()=>{const files={html:"<main><h1>Dublin Quest</h1><button id='go'>Start</button></main>",css:"body{font-family:sans-serif}",javascript:"document.querySelector('#go').addEventListener('click',()=>document.body.dataset.started='true')"};assert.equal(validateMakerFiles(files).valid,true);assert.match(makeSrcdoc(files),/Content-Security-Policy/);assert.equal(validateMakerFiles({...files,javascript:"fetch('https://example.com')"}).valid,false);assert.equal(validateMakerFiles({...files,html:'<script src="https://evil.example/x.js"></script><main><h1>X</h1></main>'}).valid,false)});
test("validator distinguishes ordinary wording from dangerous constructors and parent access",()=>{const files={html:"<main><h1>Test</h1></main>",css:"",javascript:"[1].forEach(function (item) { console.log(item); }); const label = 'For each parent and child';"};assert.equal(validateMakerFiles(files).valid,true);assert.equal(validateMakerFiles({...files,javascript:"const run = new Function('return 1');"}).valid,false);assert.equal(validateMakerFiles({...files,javascript:"parent.postMessage('x', '*');"}).valid,false)});
test("live weather or route requests cannot be embedded in Maker output",()=>{const files={html:"<main><h1>Plan</h1></main>",css:"",javascript:"fetch('https://api.open-meteo.com').then(()=>{})"};const result=validateMakerFiles(files);assert.equal(result.valid,false);assert.ok(result.errors.includes("network requests are forbidden"))});
test("rate limiter allows five starts and blocks the sixth",async()=>{const id=`test-${Date.now()}`;for(let i=0;i<5;i++)assert.equal(await consumeRateLimit(id),true);assert.equal(await consumeRateLimit(id),false)});
test("sanitiser removes external and inline executable content",()=>{const clean=sanitiseMakerFiles({html:'<link href="https://x"><main><h1>X</h1><button onclick="bad()">Go</button><iframe src="https://x"></iframe></main>',css:'@import "https://x";',javascript:""});assert.equal(validateMakerFiles(clean).valid,true);assert.doesNotMatch(clean.html,/onclick|iframe|link/i)});
test("Claude usage is costed and attributed per agent",()=>{const tracker=createUsageTracker({}, {max_calls:2,max_estimated_cost_usd:1});tracker.beforeCall();tracker.record("Designer",{input_tokens:1000,output_tokens:200});assert.equal(tracker.state.calls,1);assert.equal(tracker.state.agents.Designer.output_tokens,200);assert.equal(tracker.state.estimated_cost_usd,0.002);assert.equal(estimateHaikuCost({input_tokens:1000,output_tokens:200}),0.002)});
test("Claude usage tracker enforces both safety ceilings",()=>{const calls=createUsageTracker({calls:2},{max_calls:2,max_estimated_cost_usd:1});assert.throws(()=>calls.beforeCall(),/RUN_BUDGET_CALL_LIMIT/);const cost=createUsageTracker({estimated_cost_usd:0.2},{max_calls:9,max_estimated_cost_usd:0.2});assert.throws(()=>cost.beforeCall(),/RUN_BUDGET_COST_LIMIT/)});
