import { injectHeroMedia, makeSrcdoc } from "./src/code-validator.js";
const API=window.APP_CONFIG?.apiBase||"http://localhost:3000/api/runs",form=document.querySelector("#brief-form"),agents=[["Researcher","Identifies the opportunity"],["Designer","Creates the solution"],["Maker","Builds the product"],["Communicator","Plans customer engagement"],["Manager","Validates viability and value"]];
const draftKey="experienceCompassDraft";function saveDraft(){const values={};for(const control of form.querySelectorAll("input,textarea,select")){if(control.name)values[control.name]=control.value}sessionStorage.setItem(draftKey,JSON.stringify({values}))}function restoreDraft(){try{const draft=JSON.parse(sessionStorage.getItem(draftKey)||"null");if(!draft)return;for(const control of form.querySelectorAll("input,textarea,select")){if(control.name&&control.name in draft.values)control.value=draft.values[control.name]}}catch{sessionStorage.removeItem(draftKey)}}restoreDraft();form.addEventListener("input",saveDraft);form.addEventListener("change",saveDraft);
const formError=document.querySelector("#form-error"),submitButton=document.querySelector("#submit"),controls=()=>[...form.querySelectorAll("input,textarea,select")];function validateForm(){const invalid=controls().find(control=>!control.checkValidity());if(!invalid){formError.hidden=true;return true}const label=invalid.closest("label")?.childNodes[0]?.textContent?.trim()||"a required field";formError.textContent=`Please complete: ${label}.`;formError.hidden=false;invalid.focus();invalid.reportValidity();return false}form.noValidate=true;submitButton.addEventListener("click",validateForm);
function pipeline(status){const at=({queued:0,researching:0,designing:1,building:2,communicating:3,reviewing:4,approved:5,revision_required:5,rejected:5})[status]??0;document.querySelector("#pipeline").innerHTML=agents.map(([name,role],i)=>`<li class="${i<at?"done":i===at?"active":""}"><strong>${name}</strong><br>${role}</li>`).join("");if(at<5){document.querySelector("#working-title").textContent=`${agents[at][0]} is ${["grounding the attraction in relevant sources","choosing and designing the experience","building the webpage","planning visitor engagement","reviewing the operation"][at]}.`;document.querySelector("#working-copy").textContent=["Google Places identifies the attraction; web search adds relevant historical or cultural context.","A treasure hunt or interactive timeline will be selected and specified.","HTML, CSS and JavaScript are being created and validated.","Messages, touchpoints and measurable actions are being prepared.","Evidence, function, accessibility and business value are being checked."][at]}}
const wait=ms=>new Promise(r=>setTimeout(r,ms));async function request(id){const res=await fetch(`${API}?run_id=${encodeURIComponent(id)}`),data=await res.json();if(!res.ok)throw new Error(data.error||"REQUEST_FAILED");return data}async function poll(id){for(let i=0;i<110;i++){const run=await request(id);pipeline(run.status);if(["approved","revision_required","rejected","failed"].includes(run.status))return run;await wait(3000)}throw new Error("PIPELINE_TIMEOUT")}
async function advance(id){for(let i=0;i<5;i++){let run=await request(id);pipeline(run.status);if(["approved","revision_required","rejected","failed"].includes(run.status))return run;const res=await fetch(API,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"advance",run_id:id})}),data=await res.json();if(!data.run_id)throw new Error(data.error||"ADVANCE_FAILED")}return request(id)}
function esc(v=""){const e=document.createElement("span");e.textContent=String(v);return e.innerHTML}
const items=(values=[])=>values.length?`<ul>${values.map(value=>`<li>${esc(value)}</li>`).join("")}</ul>`:"<p>None recorded.</p>";
function agentDeliveries(outputs){
  const r=outputs.researcher,d=outputs.designer,m=outputs.maker,c=outputs.communicator,g=outputs.manager;
  return `<div class="deliveries">
    <article class="delivery"><p class="kicker">Researcher delivered to Designer</p><h3>Evidence and opportunity</h3><p>${esc(r.opportunity_diagnosis)}</p><strong>Research brief</strong><p>${esc(r.research_brief)}</p><strong>Evidence used</strong>${items(r.evidence_items.map(x=>`${x.label}: ${x.fact}`))}</article>
    <article class="delivery"><p class="kicker">Designer delivered to Maker</p><h3>${esc(d.selected_product.replaceAll("_"," "))}</h3><p>${esc(d.experience_concept)}</p><strong>Why visit now</strong><p>${esc(d.why_visit_now)}</p><strong>Signature moment</strong><p>${esc(d.signature_moment)}</p><strong>Supporting moments</strong>${items(d.supporting_moments)}<strong>Navigation</strong>${items(d.navigation_sections||d.information_architecture)}<strong>Gamification</strong>${items(d.gamification_mechanics||d.interaction_specification)}${d.reward_strategy?`<strong>Contextual reward</strong><p>${esc(d.reward_strategy.title)} — ${esc(d.reward_strategy.description)} <em>(${esc(d.reward_strategy.operational_status.replaceAll("_"," "))})</em></p>`:""}<strong>Acceptance criteria</strong>${items(d.acceptance_criteria)}</article>
    <article class="delivery"><p class="kicker">Maker delivered to Communicator</p><h3>A working visitor webpage</h3><p>${esc(m.implementation_summary)}</p><strong>Implemented features</strong>${items(m.implemented_features)}<strong>Known limitations</strong>${items(m.known_limitations)}</article>
    <article class="delivery"><p class="kicker">Communicator delivered to Manager</p><h3>Launch package</h3><p>${esc(c.value_proposition)}</p><strong>Touchpoints</strong>${items(c.visitor_touchpoints)}<strong>Launch sequence</strong>${items(c.launch_sequence)}</article>
    <article class="delivery"><p class="kicker">Manager's final decision</p><h3>${esc(g.decision.replaceAll("_"," "))}</h3><p>${esc(g.executive_summary)}</p><strong>Validation checks</strong>${items(g.validation_checks.map(x=>`${x.result.toUpperCase()}: ${x.requirement} — ${x.evidence}`))}<strong>Risks</strong>${items(g.risks)}</article>
  </div>`;
}
async function resolvedMakerFiles(run){const photo=run.media?.hero_photo,attribution=photo?.author_attributions?.[0];let data="";if(photo){try{const response=await fetch(`${API.replace(/\/runs$/,"/photo")}?run_id=${encodeURIComponent(run.id)}`);if(response.ok){const blob=await response.blob();data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob)})}}catch{}}return injectHeroMedia(run.outputs.maker.files,data,{label:attribution?.display_name?`Photo by ${attribution.display_name} on Google Maps`:`Photo of ${photo?.place_name||"the attraction"} from Google Maps`,url:attribution?.uri||photo?.google_maps_uri||""})}
async function render(run){
  document.querySelector("#working").hidden=true;const root=document.querySelector("#result");root.hidden=false;
  if(run.status==="failed"){const credit=String(run.error||"").includes("credit balance"),budget=String(run.error||"").includes("RUN_BUDGET_");const message=credit?"The Claude API account has insufficient credit. No further agent calls were made.":budget?"This run reached its safety budget and was stopped before further charges. No incomplete experience was shown.":"One agent could not complete a valid handoff. No incomplete experience was shown. Please start again.";root.innerHTML=`<div class="error-card"><p class="kicker">Run ${esc(run.id)}</p><h2>The pipeline stopped safely.</h2><p>${esc(message)}</p><button class="primary" id="restart">Start again</button></div>`;root.querySelector("#restart").onclick=()=>{location.href=location.pathname};return}
  const manager=run.outputs.manager,maker=run.outputs.maker,approved=run.status==="approved",cost=Number(run.usage?.estimated_cost_usd||0).toFixed(3);
  root.innerHTML=`<div class="result-head"><span class="status">Manager · ${esc(run.status.replace("_"," "))}</span><p class="kicker">${esc(maker.product_type.replaceAll("_"," "))}</p><h2>${esc(maker.product_title)}</h2><p>${esc(manager.executive_summary)}</p>${approved?`<a class="button primary product-link" href="experience.html?run_id=${encodeURIComponent(run.id)}" target="_blank" rel="noopener">Open the visitor experience ↗</a>`:""}</div>${approved?'<iframe class="experience-frame" title="Preview of experience created by Maker" sandbox="allow-scripts allow-popups"></iframe>':'<div class="error-card"><h2>Not launch-ready</h2><p>The Manager requires changes before launch.</p></div>'}<section class="creation-report"><p class="kicker">How it was created</p><h2>What each agent delivered</h2><p>These are the actual outputs passed through the workflow, not generic role descriptions.</p>${agentDeliveries(run.outputs)}</section><details><summary>Handoff validation trail</summary>${run.handoffs.map(h=>`<div class="handoff"><strong>${esc(h.from)} → ${esc(h.to)}</strong> · validated</div>`).join("")}</details><p><small>Run ID: ${esc(run.id)} · Claude usage: ${esc(run.usage?.calls||0)} calls, estimated $${esc(cost)} · Prompt: ${esc(run.prompt_version)}</small></p>`;
  if(approved)root.querySelector("iframe").srcdoc=makeSrcdoc(await resolvedMakerFiles(run));root.scrollIntoView({behavior:"smooth"});
}
form.addEventListener("submit",async e=>{e.preventDefault();if(!validateForm())return;submitButton.disabled=true;submitButton.textContent="Starting agents…";const formData=new FormData(form),briefing=Object.fromEntries(formData);briefing.desired_duration_minutes=Math.round(Number(briefing.desired_duration_hours)*60);delete briefing.desired_duration_hours;document.querySelector("#briefing").hidden=true;document.querySelector("#working").hidden=false;pipeline("queued");try{const res=await fetch(API,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({briefing})}),data=await res.json();if(!data.run_id)throw new Error(data.details?.join(", ")||data.error);sessionStorage.setItem("experienceCompassRun",data.run_id);history.replaceState(null,"",`?run_id=${encodeURIComponent(data.run_id)}`);const run=await advance(data.run_id);sessionStorage.removeItem("experienceCompassRun");if(run.status!=="failed")sessionStorage.removeItem(draftKey);render(run)}catch(err){const id=new URLSearchParams(location.search).get("run_id");if(id){try{return render(await request(id))}catch{}}render({id:"not-created",status:"failed",error:err.message})}});
const shared=new URLSearchParams(location.search).get("run_id"),pending=shared||sessionStorage.getItem("experienceCompassRun");if(pending){document.querySelector("#briefing").hidden=true;document.querySelector("#working").hidden=false;pipeline("queued");(shared?request(pending):advance(pending)).then(render).catch(err=>render({id:pending,status:"failed",error:err.message}))}
