const timeout=()=>AbortSignal.timeout(18000);
async function responseJson(url,options={}){const response=await fetch(url,{...options,signal:timeout()});if(!response.ok)throw new Error(`EXTERNAL_API_${response.status}_${(await response.text()).slice(0,700)}`);return response.json()}

export async function searchPlaces({query,destination,open_now=false,min_rating=0,page_size=10}){
  if(!process.env.GOOGLE_MAPS_API_KEY)throw new Error("GOOGLE_MAPS_NOT_CONFIGURED");
  const fields=["places.id","places.displayName","places.formattedAddress","places.location","places.primaryType","places.businessStatus","places.currentOpeningHours","places.rating","places.userRatingCount","places.priceLevel","places.accessibilityOptions","places.googleMapsUri"];
  const data=await responseJson("https://places.googleapis.com/v1/places:searchText",{method:"POST",headers:{"content-type":"application/json","X-Goog-Api-Key":process.env.GOOGLE_MAPS_API_KEY,"X-Goog-FieldMask":fields.join(",")},body:JSON.stringify({textQuery:`${query} in ${destination}`,openNow:Boolean(open_now),minRating:Number(min_rating)||undefined,pageSize:Math.min(15,Math.max(1,Number(page_size)||10)),languageCode:"en"})});
  const results=(data.places??[]).map(place=>({entity_id:`place:${place.id}`,label:place.displayName?.text||"Unnamed place",type:place.primaryType||null,address:place.formattedAddress||null,location:place.location||null,business_status:place.businessStatus||null,open_now:place.currentOpeningHours?.openNow??null,current_hours:place.currentOpeningHours?.weekdayDescriptions??[],rating:place.rating??null,user_rating_count:place.userRatingCount??null,price_level:place.priceLevel??null,accessibility:place.accessibilityOptions??null,source_url:place.googleMapsUri||`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(place.displayName?.text||query)}`}));
  return{provider:"Google Places",query:`${query} in ${destination}`,queried_at:new Date().toISOString(),result_count:results.length,results};
}

async function geocode(location){const url=new URL("https://geocoding-api.open-meteo.com/v1/search");url.searchParams.set("name",location);url.searchParams.set("count","1");url.searchParams.set("language","en");const data=await responseJson(url);const item=data.results?.[0];if(!item)throw new Error("WEATHER_LOCATION_NOT_FOUND");return{latitude:item.latitude,longitude:item.longitude,label:[item.name,item.admin1,item.country].filter(Boolean).join(", ")}}
export async function getWeather({location,forecast_days=3}){const geo=await geocode(location),url=new URL("https://api.open-meteo.com/v1/forecast");url.searchParams.set("latitude",geo.latitude);url.searchParams.set("longitude",geo.longitude);url.searchParams.set("current","temperature_2m,precipitation,rain,weather_code,wind_speed_10m");url.searchParams.set("daily","weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,precipitation_sum,wind_speed_10m_max");url.searchParams.set("forecast_days",String(Math.min(7,Math.max(1,Number(forecast_days)||3))));url.searchParams.set("timezone","auto");const data=await responseJson(url);return{provider:"Open-Meteo",location:geo,queried_at:new Date().toISOString(),current:data.current,daily:data.daily,source_url:"https://open-meteo.com/",result_count:(data.daily?.time??[]).length}}

export async function computeRoute({origin,destination,travel_mode="WALK",intermediates=[]}){
  if(!process.env.GOOGLE_MAPS_API_KEY)throw new Error("GOOGLE_MAPS_NOT_CONFIGURED");
  const waypoint=point=>({location:{latLng:{latitude:Number(point.latitude),longitude:Number(point.longitude)}}});
  const body={origin:waypoint(origin),destination:waypoint(destination),intermediates:intermediates.map(waypoint),travelMode:travel_mode,computeAlternativeRoutes:false,languageCode:"en-GB",units:"METRIC"};
  const data=await responseJson("https://routes.googleapis.com/directions/v2:computeRoutes",{method:"POST",headers:{"content-type":"application/json","X-Goog-Api-Key":process.env.GOOGLE_MAPS_API_KEY,"X-Goog-FieldMask":"routes.distanceMeters,routes.duration,routes.legs.distanceMeters,routes.legs.duration"},body:JSON.stringify(body)}),route=data.routes?.[0];
  return{provider:"Google Routes",queried_at:new Date().toISOString(),travel_mode,distance_meters:route?.distanceMeters??null,duration:route?.duration??null,legs:route?.legs??[],result_count:route?1:0,source_url:"https://developers.google.com/maps/documentation/routes"};
}

export const externalToolDefinitions=[
  {name:"get_weather",description:"Get current conditions and a short forecast from Open-Meteo. Use only when weather materially affects the visitor problem or proposed experience.",input_schema:{type:"object",properties:{location:{type:"string"},forecast_days:{type:"integer",minimum:1,maximum:7}},required:["location","forecast_days"],additionalProperties:false}},
  ...(process.env.GOOGLE_MAPS_API_KEY?[{name:"search_places",description:"Search Google Places for current real-world attractions or businesses. Use when discovering operational places, opening status, ratings, location, price or accessibility is relevant.",input_schema:{type:"object",properties:{query:{type:"string"},destination:{type:"string"},open_now:{type:"boolean"},min_rating:{type:"number",minimum:0,maximum:5},page_size:{type:"integer",minimum:1,maximum:15}},required:["query","destination","open_now","min_rating","page_size"],additionalProperties:false}},{name:"compute_route",description:"Calculate distance and travel duration with Google Routes. Use only if the briefing permits movement and candidate coordinates are already known. Supported modes are WALK, DRIVE and TRANSIT.",input_schema:{type:"object",properties:{origin:{type:"object",properties:{latitude:{type:"number"},longitude:{type:"number"}},required:["latitude","longitude"],additionalProperties:false},destination:{type:"object",properties:{latitude:{type:"number"},longitude:{type:"number"}},required:["latitude","longitude"],additionalProperties:false},intermediates:{type:"array",items:{type:"object",properties:{latitude:{type:"number"},longitude:{type:"number"}},required:["latitude","longitude"],additionalProperties:false}},travel_mode:{type:"string",enum:["WALK","DRIVE","TRANSIT"]}},required:["origin","destination","intermediates","travel_mode"],additionalProperties:false}}]:[])
];

export async function executeExternalTool(name,input){if(name==="search_places")return searchPlaces(input);if(name==="get_weather")return getWeather(input);if(name==="compute_route")return computeRoute(input);throw new Error(`UNKNOWN_TOOL_${name}`)}
