import {agents} from "../../agents/definitions.js";import{validateHandoff}from"../../src/contracts.js";import{sanitiseMakerFiles,validateMakerFiles}from"../../src/code-validator.js";import{callResearcherWithTool,callStructured}from"./anthropic.js";import{searchWikidata}from"./wikidata.js";import{saveRun}from"./storage.js";
const terminal=new Set(["approved","revision_required","rejected","failed"]);
export async function executeNextStage(run){if(terminal.has(run.status))return run;try{
if(run.status==="queued"){run.status="researching";await saveRun(run);const r=await callResearcherWithTool(agents.researcher,run.briefing,searchWikidata),v=validateHandoff("researcher",r.output);if(!v.valid)throw new Error(`RESEARCHER_CONTRACT:${v.errors.join("|")}`);run.tool_call=r.tool_call;run.outputs.researcher=r.output;run.handoffs.push({from:"researcher",to:"designer",validated:true,at:new Date().toISOString()});run.status="designing";await saveRun(run);return run}
if(run.status==="researching")return run;
if(run.status==="designing"){const r=await callStructured(agents.designer,{briefing:run.briefing,researcher:run.outputs.researcher}),v=validateHandoff("designer",r.output,run.outputs);if(!v.valid)throw new Error(`DESIGNER_CONTRACT:${v.errors.join("|")}`);run.outputs.designer=r.output;run.handoffs.push({from:"designer",to:"maker",validated:true,at:new Date().toISOString()});run.status="building";await saveRun(run);return run}
if(run.status==="building"){const r=await callStructured(agents.maker,{briefing:run.briefing,researcher:run.outputs.researcher,designer:run.outputs.designer});r.output.files=sanitiseMakerFiles(r.output.files);const v=validateHandoff("maker",r.output,run.outputs),code=validateMakerFiles(r.output.files);run.validations.code=code;if(!v.valid||!code.valid)throw new Error(`MAKER_VALIDATION:${[...v.errors,...code.errors].join("|")}`);run.outputs.maker=r.output;run.handoffs.push({from:"maker",to:"communicator",validated:true,at:new Date().toISOString()});run.status="communicating";await saveRun(run);return run}
if(run.status==="communicating"){const r=await callStructured(agents.communicator,{briefing:run.briefing,designer:run.outputs.designer,maker:{...run.outputs.maker,files:"validated files supplied separately"}}),v=validateHandoff("communicator",r.output,run.outputs);if(!v.valid)throw new Error(`COMMUNICATOR_CONTRACT:${v.errors.join("|")}`);run.outputs.communicator=r.output;run.handoffs.push({from:"communicator",to:"manager",validated:true,at:new Date().toISOString()});run.status="reviewing";await saveRun(run);return run}
if(run.status==="reviewing"){const r=await callStructured(agents.manager,{briefing:run.briefing,tool_call:run.tool_call,researcher:run.outputs.researcher,designer:run.outputs.designer,maker:run.outputs.maker,code_validation:run.validations.code,communicator:run.outputs.communicator,handoffs:run.handoffs}),v=validateHandoff("manager",r.output,run.outputs);if(!v.valid)throw new Error(`MANAGER_CONTRACT:${v.errors.join("|")}`);run.outputs.manager=r.output;run.status=r.output.decision;run.completed_at=new Date().toISOString();await saveRun(run);return run}
}catch(error){run.status="failed";run.error=error instanceof Error?error.message:"UNKNOWN_ERROR";run.completed_at=new Date().toISOString();await saveRun(run);return run}}
