import {agents} from "../../agents/definitions.js";import{validateHandoff}from"../../src/contracts.js";import{sanitiseMakerFiles,validateMakerFiles}from"../../src/code-validator.js";import{callResearcherWithTools,callStructured}from"./anthropic.js";import{externalToolDefinitions,executeExternalTool}from"./external-tools.js";import{saveRun}from"./storage.js";
const terminal=new Set(["approved","revision_required","rejected","failed"]);
export async function executeNextStage(run){if(terminal.has(run.status))return run;try{
if(run.status==="queued"){run.status="researching";await saveRun(run)}
if(run.status==="researching"){const r=await callResearcherWithTools(agents.researcher,run.briefing,externalToolDefinitions,executeExternalTool),v=validateHandoff("researcher",r.output);if(!v.valid)throw new Error(`RESEARCHER_CONTRACT:${v.errors.join("|")}`);run.tool_calls=r.tool_calls;run.outputs.researcher=r.output;run.handoffs.push({from:"researcher",to:"designer",validated:true,at:new Date().toISOString()});run.status="designing";await saveRun(run);return run}
if(run.status==="designing"){const r=await callStructured(agents.designer,{briefing:run.briefing,researcher:run.outputs.researcher}),v=validateHandoff("designer",r.output,run.outputs);if(!v.valid)throw new Error(`DESIGNER_CONTRACT:${v.errors.join("|")}`);run.outputs.designer=r.output;run.handoffs.push({from:"designer",to:"maker",validated:true,at:new Date().toISOString()});run.status="building";await saveRun(run);return run}
if(run.status==="building"){const input={briefing:run.briefing,researcher:run.outputs.researcher,designer:run.outputs.designer};let r,v,code,errors=[];for(let attempt=0;attempt<3;attempt++){r=await callStructured(agents.maker,attempt===0?input:{...input,previous_attempt_rejected:errors,correction_instruction:`Rebuild from scratch. Attempt ${attempt+1} must include non-empty semantic HTML with main and h1, CSS and JavaScript. Do not use localStorage, sessionStorage, indexedDB, network requests, parent-window access, Function, eval, inline event attributes or any previously rejected pattern. Keep state only in JavaScript memory and attach events with addEventListener.`});r.output.files=sanitiseMakerFiles(r.output.files);v=validateHandoff("maker",r.output,run.outputs);code=validateMakerFiles(r.output.files);errors=[...v.errors,...code.errors];if(!errors.length)break;run.validations.maker_attempts=attempt+1}run.validations.code=code;if(errors.length)throw new Error(`MAKER_VALIDATION:${errors.join("|")}`);run.outputs.maker=r.output;run.handoffs.push({from:"maker",to:"communicator",validated:true,at:new Date().toISOString()});run.status="communicating";await saveRun(run);return run}
if(run.status==="communicating"){const r=await callStructured(agents.communicator,{briefing:run.briefing,designer:run.outputs.designer,maker:{...run.outputs.maker,files:"validated files supplied separately"}}),v=validateHandoff("communicator",r.output,run.outputs);if(!v.valid)throw new Error(`COMMUNICATOR_CONTRACT:${v.errors.join("|")}`);run.outputs.communicator=r.output;run.handoffs.push({from:"communicator",to:"manager",validated:true,at:new Date().toISOString()});run.status="reviewing";await saveRun(run);return run}
if(run.status==="reviewing"){const r=await callStructured(agents.manager,{briefing:run.briefing,tool_calls:run.tool_calls,researcher:run.outputs.researcher,designer:run.outputs.designer,maker:run.outputs.maker,code_validation:run.validations.code,communicator:run.outputs.communicator,handoffs:run.handoffs}),v=validateHandoff("manager",r.output,run.outputs);if(!v.valid)throw new Error(`MANAGER_CONTRACT:${v.errors.join("|")}`);run.outputs.manager=r.output;run.status=r.output.decision;run.completed_at=new Date().toISOString();await saveRun(run);return run}
}catch(error){run.status="failed";run.error=error instanceof Error?error.message:"UNKNOWN_ERROR";run.completed_at=new Date().toISOString();await saveRun(run);return run}}
