const strings = { type: "array", items: { type: "string" } };
const base = (properties, required) => ({ type: "object", properties, required, additionalProperties: false });

export const agents = {
  researcher: {
    name: "Researcher", archetype: "Researcher - Identify the opportunity",
    system: `You are the research lead for a visitor-attraction experience. First use Google Places to identify and ground the named attraction in current external data. Use web search only when it materially supplies historical, cultural or interpretive context for the client's existing stories, objects or areas. Explain each call in tool_decisions. Distinguish the client's supplied content from externally verified facts, and never treat ratings as proof of visitor behaviour. Never claim opening hours, accessibility or historical facts unless a source returned them; label estimates, conflicts and unknowns. Do not choose or design the product. Every evidence item must have a stable unique ID, URL and source_query_id.`,
    schema: base({ research_question:{type:"string"}, opportunity_diagnosis:{type:"string"}, audience_needs:strings, business_needs:strings, tool_decisions:{type:"array",items:base({tool:{type:"string"},decision:{type:"string",enum:["used","not_used"]},rationale:{type:"string"}},["tool","decision","rationale"])},source_queries:{type:"array",items:base({source_query_id:{type:"string"},tool:{type:"string"},query:{type:"string"},queried_at:{type:"string"},result_count:{type:"integer"}},["source_query_id","tool","query","queried_at","result_count"])}, evidence_items:{type:"array",minItems:1,items:base({entity_id:{type:"string"},source_query_id:{type:"string"},label:{type:"string"},fact:{type:"string"},source_url:{type:"string"},relevance:{type:"string"}},["entity_id","source_query_id","label","fact","source_url","relevance"])}, experience_opportunities:strings, constraints:strings, unknowns:strings, research_brief:{type:"string"} }, ["research_question","opportunity_diagnosis","audience_needs","business_needs","tool_decisions","source_queries","evidence_items","experience_opportunities","constraints","unknowns","research_brief"])
  },
  designer: {
    name: "Designer", archetype: "Designer - Create the solution",
    system: `You are an inventive visitor-attraction experience designer. Using only the briefing and Researcher evidence, select exactly one of treasure_hunt or interactive_timeline. Choose treasure_hunt when active discovery, clues and progression best solve the problem; choose interactive_timeline when chronology, causality or change over time is central. Define an original journey, interaction logic, information architecture, accessibility, visual direction and testable acceptance criteria for this attraction. Do not write code or marketing copy. required_evidence_ids may contain only exact entity_id values present in the Researcher evidence_items.`,
    schema: base({selected_product:{type:"string",enum:["treasure_hunt","interactive_timeline"]},selection_rationale:{type:"string"},design_goal:{type:"string"},experience_concept:{type:"string"},visitor_journey:strings,information_architecture:strings,interaction_specification:strings,required_evidence_ids:strings,content_requirements:strings,visual_direction:{type:"string"},accessibility_requirements:strings,functional_requirements:strings,acceptance_criteria:strings,known_tradeoffs:strings},["selected_product","selection_rationale","design_goal","experience_concept","visitor_journey","information_architecture","interaction_specification","required_evidence_ids","content_requirements","visual_direction","accessibility_requirements","functional_requirements","acceptance_criteria","known_tradeoffs"])
  },
  maker: {
    name: "Maker", archetype: "Maker - Build the product",
    system: `You are a senior frontend prototyper. Build the complete, original treasure hunt or interactive timeline specified by the Designer using the supplied attraction content and sourced evidence. Deliver semantic HTML for the body (including main and h1), self-contained CSS and self-contained JavaScript; keep their combined code below 9000 characters. Implement the essential interactions, progress/state, responsive behaviour and keyboard accessibility concisely. The evidence is a creation-time snapshot: do not imply that opening hours or operational details are live. A deterministic validator rejects every HTML attribute beginning with on; attach events only with addEventListener. Never use eval or the Function constructor. Use no external libraries, assets, network requests, storage APIs, imports, navigation, parent access, forms with actions or device permissions. Do not change the selected category. Report every acceptance criterion honestly; if it cannot be implemented, set build_status incomplete.`,
    schema: base({product_type:{type:"string",enum:["treasure_hunt","interactive_timeline"]},product_title:{type:"string"},implementation_summary:{type:"string"},files:base({html:{type:"string"},css:{type:"string"},javascript:{type:"string"}},["html","css","javascript"]),implemented_features:strings,evidence_trace:{type:"array",items:base({interface_element:{type:"string"},evidence_id:{type:"string"}},["interface_element","evidence_id"])},usage_instructions:strings,acceptance_check:{type:"array",items:base({criterion:{type:"string"},result:{type:"string",enum:["pass","fail"]},evidence:{type:"string"}},["criterion","result","evidence"])},known_limitations:strings,build_status:{type:"string",enum:["ready","incomplete","unsafe"]}},["product_type","product_title","implementation_summary","files","implemented_features","evidence_trace","usage_instructions","acceptance_check","known_limitations","build_status"])
  },
  communicator: {
    name: "Communicator", archetype: "Communicator - Get the customers",
    system: `You are a tourism customer-engagement strategist. You receive a functioning product, not an idea. Decide how the organisation should introduce it across the visitor journey. Create a concrete launch sequence, touchpoints, ready-to-use copy, calls to action and measurable engagement metrics. Mention only features the Maker actually implemented, disclose limitations, avoid pressure or unsupported performance claims, and do not alter the product.`,
    schema: base({value_proposition:{type:"string"},audience_message:{type:"string"},experience_name_and_tagline:{type:"string"},visitor_touchpoints:strings,channel_plan:strings,launch_sequence:strings,ready_to_use_copy:{type:"array",items:base({placement:{type:"string"},copy:{type:"string"},call_to_action:{type:"string"}},["placement","copy","call_to_action"])},engagement_metrics:{type:"array",items:base({metric:{type:"string"},purpose:{type:"string"},collection_method:{type:"string"}},["metric","purpose","collection_method"])},communication_risks:strings},["value_proposition","audience_message","experience_name_and_tagline","visitor_touchpoints","channel_plan","launch_sequence","ready_to_use_copy","engagement_metrics","communication_risks"])
  },
  manager: {
    name: "Manager", archetype: "Manager - Run the business",
    system: `You are the accountable tourism product manager. Review the original briefing, Researcher evidence, Designer specification, Maker webpage and validation results, and Communicator launch plan. Verify the exact unbroken handoff, source traceability, product/category integrity, acceptance criteria, accessibility, truthful communication, feasibility and business value. Do not approve when code validation fails, evidence is invented, the product does not work, or communication describes absent features. Produce an executive summary and operational plan. Attribute each correction to the responsible agent. Approval means launch-ready prototype, not guaranteed business impact.`,
    schema: base({decision:{type:"string",enum:["approved","revision_required","rejected"]},validation_checks:{type:"array",items:base({requirement:{type:"string"},result:{type:"string",enum:["pass","fail"]},evidence:{type:"string"}},["requirement","result","evidence"])},issues:{type:"array",items:base({severity:{type:"string",enum:["critical","major","minor"]},responsible_agent:{type:"string"},finding:{type:"string"},required_change:{type:"string"}},["severity","responsible_agent","finding","required_change"])},executive_summary:{type:"string"},operational_plan:strings,launch_conditions:strings,success_metrics:strings,risks:strings,future_improvements:strings},["decision","validation_checks","issues","executive_summary","operational_plan","launch_conditions","success_metrics","risks","future_improvements"])
  }
};
