const text = {type:"string",description:"One concise paragraph, no more than 600 characters."};
const shortText = {type:"string",description:"One concise statement, no more than 300 characters."};
const strings = {type:"array",description:"At most four short items, each no more than 240 characters.",items:{type:"string"}};
const base = (properties, required) => ({ type: "object", properties, required, additionalProperties: false });

export const agents = {
  researcher: {
    name: "Researcher", archetype: "Researcher - Identify the opportunity",
    system: `You are the research lead for a visitor-attraction experience. First use Google Places to identify and ground the named attraction in current external data. Then use focused web research when it materially supplies historical, cultural, interpretive or visitor-relevant context for the client's existing stories, objects or areas. Deliver enough grounded material for a rich three-area visitor microsite: identity and significance, stories or observable details, and opportunities for contextual gamification. The product is always a mobile-first webpage opened from a normal URL: never recommend QR scans, location checks, special equipment or unprovided operational resources. Explain each call in tool_decisions. Distinguish the client's supplied content from externally verified facts, and never treat ratings as proof of visitor behaviour. Never claim opening hours, accessibility, rewards or historical facts unless a source returned them; label estimates, conflicts and unknowns. Do not choose or design the product. Every evidence item must have a stable unique ID, URL and source_query_id.`,
    schema: base({research_question:shortText,opportunity_diagnosis:text,audience_needs:strings,business_needs:strings,tool_decisions:{type:"array",description:"At most three tool decisions.",items:base({tool:shortText,decision:{type:"string",enum:["used","not_used"]},rationale:shortText},["tool","decision","rationale"])},source_queries:{type:"array",description:"At most four source queries.",items:base({source_query_id:shortText,tool:shortText,query:shortText,queried_at:shortText,result_count:{type:"integer"}},["source_query_id","tool","query","queried_at","result_count"])},evidence_items:{type:"array",description:"Four to six strongest evidence items across identity, stories and observable details.",items:base({entity_id:shortText,source_query_id:shortText,label:shortText,fact:text,source_url:{type:"string",description:"Source URL."},relevance:shortText},["entity_id","source_query_id","label","fact","source_url","relevance"])},experience_opportunities:strings,constraints:strings,unknowns:strings,research_brief:text},["research_question","opportunity_diagnosis","audience_needs","business_needs","tool_decisions","source_queries","evidence_items","experience_opportunities","constraints","unknowns","research_brief"])
  },
  designer: {
    name: "Designer", archetype: "Designer - Create the solution",
    system: `You are an inventive visitor-attraction experience designer. Using only the briefing and Researcher evidence, select exactly one of treasure_hunt or interactive_timeline. Choose treasure_hunt for active discovery and interactive_timeline for chronology or change over time. Design one polished visitor microsite with three clearly navigable areas: Discover (grounded place context and highlights), Experience (exactly four varied interactive missions or moments with visible progress and meaningful feedback), and Reward (a contextual unlock earned on completion). The reward must creatively fit the attraction: a recipe, hidden story, collection, observation guide, digital keepsake or other evidence-compatible unlock. A physical leaflet, stamp, sample or gift may only be a proposal_requires_approval and must never be presented as available. Make the narrative, game mechanic, visual direction and reward specific to this attraction and audience, not a generic card template. Use the supplied Google Places hero media and require visible attribution, but do not invent other assets. The experience is always mobile-first and reached through a normal webpage link. It must work entirely in the browser with no QR code or scan, accounts, backend, analytics, audio, sharing, location, storage, special equipment or unsupported verification. Observation questions, choices and self-checks are allowed; never imply GPS or physical-presence verification. Do not write code or acquisition marketing copy. required_evidence_ids may contain only exact entity_id values present in the Researcher evidence_items.`,
    schema: base({selected_product:{type:"string",enum:["treasure_hunt","interactive_timeline"]},selection_rationale:shortText,design_goal:shortText,experience_concept:text,navigation_sections:strings,visitor_journey:strings,information_architecture:strings,interaction_specification:strings,gamification_mechanics:strings,reward_strategy:base({type:{type:"string",enum:["digital_content","experiential_unlock","physical_proposal"]},title:shortText,description:text,unlock_condition:shortText,verification_method:{type:"string",enum:["observation_question","visitor_choice","self_check","staff_confirmation"]},operational_status:{type:"string",enum:["deliverable_now","proposal_requires_approval"]}},["type","title","description","unlock_condition","verification_method","operational_status"]),required_evidence_ids:strings,content_requirements:strings,visual_direction:shortText,accessibility_requirements:strings,functional_requirements:strings,acceptance_criteria:strings,known_tradeoffs:strings},["selected_product","selection_rationale","design_goal","experience_concept","navigation_sections","visitor_journey","information_architecture","interaction_specification","gamification_mechanics","reward_strategy","required_evidence_ids","content_requirements","visual_direction","accessibility_requirements","functional_requirements","acceptance_criteria","known_tradeoffs"])
  },
  maker: {
    name: "Maker", archetype: "Maker - Build the product",
    system: `You are a senior frontend prototyper. Build the Designer's polished visitor microsite, not a generic card demo. Create a strong photographic hero and three keyboard-accessible navigable views: Discover with grounded context and highlights, Experience with exactly four visually varied missions or moments plus score/progress and meaningful feedback, and Reward with a contextual locked/unlocked state. Implement the Designer's specified reward honestly. If its status is proposal_requires_approval, label it clearly as a suggested organisation activation and never claim visitors can redeem it; otherwise reveal the supplied digital or experiential content on completion. The page must feel specific to the attraction through typography, colour, composition and concise narrative detail. It is mobile-first and opened from a normal URL; never require a QR code, scan, location or special equipment. Put {{HERO_IMAGE}} in the hero img src. Put the literal {{HERO_ATTRIBUTION}} token inside a plain small or figcaption element; do not wrap it in an anchor and do not create any external link because the trusted publishing system injects the safe attribution link after approval. Deliver semantic body HTML (including main, header, nav, h1 and at least three sections), self-contained CSS and JavaScript; keep combined code below 8000 characters. Implement responsive behaviour, keyboard interaction, focus states, reduced-motion support and legible contrast. Do not add screens or features not requested. A validator rejects HTML attributes beginning with on; use addEventListener. Never use eval, Function, external libraries, other assets, network requests, storage, imports, navigation, parent access, form actions or device permissions. Do not change category. Report acceptance honestly.`,
    schema: base({product_type:{type:"string",enum:["treasure_hunt","interactive_timeline"]},product_title:shortText,implementation_summary:text,files:base({html:{type:"string",description:"Complete compact HTML, at most 4000 characters."},css:{type:"string",description:"Complete compact CSS, at most 2500 characters."},javascript:{type:"string",description:"Complete compact JavaScript, at most 1500 characters."}},["html","css","javascript"]),implemented_features:strings,evidence_trace:{type:"array",description:"At most four trace entries.",items:base({interface_element:shortText,evidence_id:shortText},["interface_element","evidence_id"])},usage_instructions:strings,acceptance_check:{type:"array",description:"At most four checks.",items:base({criterion:shortText,result:{type:"string",enum:["pass","fail"]},evidence:shortText},["criterion","result","evidence"])},known_limitations:strings,build_status:{type:"string",enum:["ready","incomplete","unsafe"]}},["product_type","product_title","implementation_summary","files","implemented_features","evidence_trace","usage_instructions","acceptance_check","known_limitations","build_status"])
  },
  communicator: {
    name: "Communicator", archetype: "Communicator - Get the customers",
    system: `You are a tourism customer-engagement strategist. You receive a functioning visitor microsite, not a future product. Create a focused launch package that explains the Discover, Experience and Reward journey and how the contextual unlock motivates completion or return. Mention only features explicitly listed by the Maker. For physical_proposal rewards, describe staff, signage and approval steps as an internal recommendation and never advertise redemption before organisation approval. Never promise accounts, analytics, audio, sharing, QR codes, location, persistence, partnerships or future functionality. Disclose limitations and do not alter the product.`,
    schema: base({value_proposition:text,audience_message:text,experience_name_and_tagline:shortText,visitor_touchpoints:strings,channel_plan:strings,launch_sequence:strings,ready_to_use_copy:{type:"array",description:"At most four copy items.",items:base({placement:shortText,copy:text,call_to_action:shortText},["placement","copy","call_to_action"])},engagement_metrics:{type:"array",description:"At most four metrics.",items:base({metric:shortText,purpose:shortText,collection_method:shortText},["metric","purpose","collection_method"])},communication_risks:strings},["value_proposition","audience_message","experience_name_and_tagline","visitor_touchpoints","channel_plan","launch_sequence","ready_to_use_copy","engagement_metrics","communication_risks"])
  },
  manager: {
    name: "Manager", archetype: "Manager - Run the business",
    system: `You are the accountable tourism product manager. Review this as a classroom visitor-microsite MVP, not a production platform. Verify source traceability, one authorised product category, three navigable areas, four working interactions, score or progress, contextual reward behaviour, accessibility and truthful communication. Reject any unsupported claim that a physical reward is available; physical_proposal must remain visibly subject to organisation approval. Verify that digital or experiential unlocks derive from supplied or sourced content. Do not demand backend, accounts, analytics, audio, sharing, QR codes or other production features. Approve when the validated prototype works and communication describes only implemented features; reserve revision_required for a real defect or mismatch. Keep the review concise and attribute corrections.`,
    schema: base({decision:{type:"string",enum:["approved","revision_required","rejected"]},validation_checks:{type:"array",description:"At most six checks.",items:base({requirement:shortText,result:{type:"string",enum:["pass","fail"]},evidence:shortText},["requirement","result","evidence"])},issues:{type:"array",description:"At most four issues.",items:base({severity:{type:"string",enum:["critical","major","minor"]},responsible_agent:shortText,finding:shortText,required_change:shortText},["severity","responsible_agent","finding","required_change"])},executive_summary:text,operational_plan:strings,launch_conditions:strings,success_metrics:strings,risks:strings,future_improvements:strings},["decision","validation_checks","issues","executive_summary","operational_plan","launch_conditions","success_metrics","risks","future_improvements"])
  }
};
